/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exemple_jni_JNIExemple */

#ifndef _Included_com_exemple_jni_JNIExemple
#define _Included_com_exemple_jni_JNIExemple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exemple_jni_JNIExemple
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exemple_jni_JNIExemple_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
